import Component from '@glimmer/component';

export default class SynthKeyboard extends Component {
  keys = [
    {
      name: 'c',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 'q',
    },
    {
      name: 'c#',
      octave: 4,
      color: 'black',
      indent: false,
      shortcut: 'w',
    },
    {
      name: 'd',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 'e',
    },
    {
      name: 'd#',
      octave: 4,
      color: 'black',
      indent: false,
      shortcut: 'r',
    },
    {
      name: 'e',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 't',
    },
    {
      name: 'f',
      octave: 4,
      color: 'white',
      indent: false,
      shortcut: 'y',
    },
    {
      name: 'f#',
      octave: 4,
      color: 'black',
      indent: false,
      shortcut: 'u',
    },
    {
      name: 'g',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 'u',
    },
    {
      name: 'g#',
      octave: 4,
      color: 'black',
      indent: false,
      shortcut: 'i',
    },
    {
      name: 'a',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 'o',
    },
    {
      name: 'a#',
      octave: 4,
      color: 'black',
      indent: false,
      shortcut: 'p',
    },
    {
      name: 'b',
      octave: 4,
      color: 'white',
      indent: true,
      shortcut: 'a',
    },
    {
      name: 'c',
      octave: 5,
      color: 'white',
      indent: false,
      shortcut: 's',
    },
    {
      name: 'c#',
      octave: 5,
      color: 'black',
      indent: false,
      shortcut: 'd',
    },
    {
      name: 'd',
      octave: 5,
      color: 'white',
      indent: true,
      shortcut: 'f',
    },
    {
      name: 'd#',
      octave: 5,
      color: 'black',
      indent: false,
      shortcut: 'g',
    },
    {
      name: 'e',
      octave: 5,
      color: 'white',
      indent: true,
      shortcut: 'h',
    },
    {
      name: 'f',
      octave: 5,
      color: 'white',
      indent: false,
      shortcut: 'j',
    },
    {
      name: 'f#',
      octave: 5,
      color: 'black',
      indent: false,
      shortcut: 'k',
    },
    {
      name: 'g',
      octave: 5,
      color: 'white',
      indent: true,
      shortcut: 'l',
    },
    {
      name: 'g#',
      octave: 5,
      color: 'black',
      indent: false,
      shortcut: 'z',
    },
    {
      name: 'a',
      octave: 5,
      color: 'white',
      indent: true,
      shortcut: 'x',
    },
    {
      name: 'a#',
      octave: 5,
      color: 'black',
      indent: false,
      shortcut: 'c',
    },
    {
      name: 'b',
      octave: 5,
      color: 'white',
      indent: true,
      shortcut: 'v',
    },
    {
      name: 'c',
      octave: 6,
      color: 'white',
      indent: false,
      shortcut: 'b',
    },
    {
      name: 'c#',
      octave: 6,
      color: 'black',
      indent: false,
      shortcut: 'n',
    },
    {
      name: 'd',
      octave: 6,
      color: 'white',
      indent: true,
      shortcut: 'm',
    },
  ];
};
